### ISSUE TITLE
hi boy

### ISSUE THREAD

**Issue by SpiritBreaker** [isnowfy/snownlp#29]
你的bm25算法，计算idf的时候用的是math.log(self.D-v+0.5)-math.log(v+0.5)，但是我看了一些文章，计算方式确实log(self.D)-log(v+1),请问这2个计算有什么区别，还是可以替换的呢？？？

**Comment by isnowfy** [comment]
都差不多的，影响不是很大，大体上都是围绕log(D/v)这样做一些小修改，可以自己测试一下选择一个适合自己的+-常数啥的

**Comment by SpiritBreaker** [comment]
ok

**Comment by cherubines** [comment]
您好，看了您的snownlp项目，可否请您授课 讲讲里面的技术细节！

**Comment by isnowfy** [comment]
@cherubines 邮件我说一下你的需求吧
