### ISSUE TITLE
Interspersed English words

### ISSUE THREAD

**Issue by hampsterx** [isnowfy/snownlp#31]
Ni Hao, I would like to be able to parse News Articles, some of which contain English words mixed within the chinese sentence.

Eg 

s = SnowNLP(u'这个东西真心很cool赞')

print s.pinyin

This results in..

[u'zhe', u'ge', u'dong', u'xi', u'zhen', u'xin', u'hen', u'c', u'o', u'o', u'l', u'zan']

:(

**Comment by isnowfy** [comment]
Thanks for your issue:)
