### ISSUE TITLE
Python 3.5 SnowNLP关键词分析每次运行结果不同

### ISSUE THREAD

**Issue by jiacheliu3** [isnowfy/snownlp#32]
比如我在一段文本里面选择10个关键词
content=...#内容
r=SnowNLP(content)
result=r.keywords(10, False)
第一次运行结果：
['執', '這', '壺', '年', '版', '星期日', '下午', '收', '也出', '土']
第二次：
['出', '年', '版', '星期日', '下午', '執壺', '種', '級', '低', '岛']
第三次：
['壺', '種', '年', '星期日', '下午', '岛', '也出', '也收藏', '物館', '明這']

我怀疑原因和python版本有关，见jieba分词的类似问题
https://github.com/fxsjy/jieba/issues/228

**Comment by isnowfy** [comment]
你用的文本是什么，我在我本地用了下3.5.0发现没有你说的问题？

**Comment by jiacheliu3** [comment]
我用的文本就是一段微博：
回复@大碗岛的星期日下午:這責問不是針對你的，你不會犯這種低級錯誤。耿寶昌在他1984年版香港中華書局出版的《明清瓷器鑑定》中已列明這種執壺的器型；前幾年江蘇也出土過類似藍釉執壺；更何況海外博物館也收藏有此類執壺。不要因為看似壺柄像鋼條，就妄下結論，做學問貴在認真兩字。, 明宣德藍釉白龍鳳紋執壺

在命令行中使用是不会这样情况的，分词几次结果都相同
>>> from snownlp import SnowNLP
>>> t=open("111.txt","r").read()
>>> r=SnowNLP(t)
>>> r.keywords(10,False)
['這', '藍', '也出', '土過', '物', '博', '星期日', '版', '蘇', '類']
>>> x=SnowNLP(t)
>>> x.keywords(10,False)
['這', '藍', '也出', '土過', '物', '博', '星期日', '版', '蘇', '類']
>>> x=open("111.txt","r").read()
>>> y=SnowNLP(x)
>>> y.keywords(10,False)
['這', '藍', '也出', '土過', '物', '博', '星期日', '版', '蘇', '類']

但是如果我把以上内容写入一个脚本，再用脚本分词同一个文件，就会出现不同的结果
C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['這', '年', '中', '藍', '似', '物', '館也', '蘇也出土過', '星期日', '下午']

C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['壺', '中', '星期日', '土', '貴', '認', '過', '岛', '下午', '物']

C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['執', '這', '問', '壺', '似', '星期日', '下午', '認', '貴', '年']

t.py的内容很简单：“111.txt”就是包含如上文本的一个txt文件，内容没有改动过
from snownlp import SnowNLP
a=open("111.txt","r").read()
b=SnowNLP(a)
c=b.keywords(10,False)
print(c)

**Comment by isnowfy** [comment]
确实有这个问题，应该是说的key的hash不同造成items顺序不同，然后浮动运算的时候，顺序不同可能会造成一些误差，于是改为从小到大的计算，话说繁体不能很好地分词，可以先转成简体再做会好一些

**Comment by jiacheliu3** [comment]
想问一下顺序不同的问题会在将来版本中解决吗？三个结果比较起来差别还是比较大的
C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['這', '年', '中', '藍', '似', '物', '館也', '蘇也出土過', '星期日', '下午']
C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['壺', '中', '星期日', '土', '貴', '認', '過', '岛', '下午', '物']
C:\Users\Tassadar\Desktop\Course\weibo\temp>python t.py
['執', '這', '問', '壺', '似', '星期日', '下午', '認', '貴', '年']

**Comment by isnowfy** [comment]
已经解决了，你是没有用最新版本吗

**Comment by jiacheliu3** [comment]
好的我去更新成最新版本 谢谢解决

**Comment by isnowfy** [comment]
多谢发现有问题:)
