### ISSUE TITLE
如何自定义情感词典

### ISSUE THREAD

**Issue by BruceDone** [isnowfy/snownlp#34]
hi,首先感谢作者做出这样一个实用的库出来，我想问如果我手上有情感词汇词典文本文件，如果和本库结合使用？thanks

**Comment by isnowfy** [comment]
现在是直接用句子训练的，用readme里说的重新训练就可以
~~~~
from snownlp import sentiment
sentiment.train('neg.txt', 'pos.txt')
sentiment.save('sentiment.marshal')
~~~~
https://github.com/isnowfy/snownlp/blob/master/snownlp/sentiment/__init__.py#L11 这行里改到你训练的文件就可以了

**Comment by BruceDone** [comment]
感谢
