### ISSUE TITLE
你好，能解释下目录结构吗，感觉有些事多余的啊？

### ISSUE THREAD

**Issue by wgliang** [isnowfy/snownlp#35]

**Comment by isnowfy** [comment]
目录结构就是英文命名的内容直接相关啊
classification文本分类
normal一些基础工作，简繁转换，拼音，停用词去除啥的
seg分词
sentiment情感分析
sim文本相似
summary关键词，关键句提取
tag词性分析
utils一些工具程序

**Comment by wgliang** [comment]
build里面为什么还有snownlp，这个build有用吗?目前在学习大神的这个，谢谢！

**Comment by isnowfy** [comment]
build是什么，哪有build文件夹？
