### ISSUE TITLE
请问分词的训练集是什么格式和规则？

### ISSUE THREAD

**Issue by dengjl** [isnowfy/snownlp#36]

**Comment by isnowfy** [comment]
人民日报的格式，可以参考这个文件https://github.com/isnowfy/snownlp/blob/master/snownlp/seg/data.txt

**Comment by dengjl** [comment]
感谢！还想请教一下，如果我在分词的训练集里只加一个一个的词，不加句子，可不可以？

**Comment by isnowfy** [comment]
理论上是可以的，不过还是加句子效果更好一些
