### ISSUE TITLE
请问文本分类的功能如何使用

### ISSUE THREAD

**Issue by sshybhy** [isnowfy/snownlp#46]
外行问题，请问特征里写到的文本分类的功能怎么使用啊？

**Comment by isnowfy** [comment]
要类似这里 https://github.com/isnowfy/snownlp/blob/master/snownlp/sentiment/__init__.py#L31 https://github.com/isnowfy/snownlp/blob/master/snownlp/sentiment/__init__.py#L40 做训练和预测就好

**Comment by sshybhy** [comment]
好的，多谢指点~~
