### ISSUE TITLE
sentiment训练后结果不变？

### ISSUE THREAD

**Issue by tangwz** [isnowfy/snownlp#48]
用自己的训练集训练：
```
def train():
    from snownlp import sentiment
    sentiment.train('filter_neg.txt', 'filter_pos.txt')
    sentiment.save('sentiment.marshal')
```

然后调用marshal进行情感分析结果输出：
```
from snownlp import sentiment
    sentiment.data_path = 'sentiment.marshal'

    with open('test.txt') as f:
        data = f.xreadlines()
        for line in data:
            line = line.decode('utf-8').replace('\r', ' ').replace('\n', ' ').replace('\t', ' ')
            snlp = SnowNLP(line)
            print snlp.sentiments
```

可是得到的结果和没有调用新的marshal一样，请问是哪里写得有问题吗？

**Comment by isnowfy** [comment]
我为了调用方便，import的时候词典就自动加载了，所以在第一步from snownlp import sentiment的时候加载了原始字典，有几种解决方案把，一个是用你的marshal文件顶替掉我的，一个是直接修改代码里的data_path，再一个就是
from snownlp import sentiment
sentiment.classifier.load('sentiment.marshal')

**Comment by tangwz** [comment]
BTW，分词对情感分析有影响吗？我需要既训练分词又训练sentiment吗？

**Comment by isnowfy** [comment]
分词影响不大，一般不用训练分词，如果你的材料里有很多专有名词，通用的分词分不出来的话最好训练分词

**Comment by tangwz** [comment]
谢谢解答。公司有人用gensim + tensorflow写了一个情感分析的，结果我用这个发现效果比他忙活很久的好一点，训练过后准确率80%左右。
看看自己能不能再改进改进。。。
