### ISSUE TITLE
Question#2 求思路-如何生成全文主语, 因为提取的summary句子缺乏主语造成误解/歧义

### ISSUE THREAD

**Issue by AndyXGWang** [isnowfy/snownlp#51]
example; 有段文字提取后的summary=“提出来一种全新的研究方案”
该句被作为textrank高分值输出，但是因为没有主语, 而容易造成误解.

请问是否有什么方法 可以得到上下文相关的主语?

Thanks & BR
Andy

**Comment by isnowfy** [comment]
可以尝试下stanfordnlp里的依存句法分析的接口来做
