### ISSUE TITLE
sentiments能说明一下吗

### ISSUE THREAD

**Issue by rainsun007** [isnowfy/snownlp#52]
s.sentiments   返回值为  5.4515365364e-05   这是不正常的吧
这个值正常来说应该是小于1的是吧

**Comment by isnowfy** [comment]
这是科学计数法，这个值表示0.00005451

**Comment by rainsun007** [comment]
多谢   了解了   如果想使用sentiments划分出 下面，负面，普通   三个分类，   数据范围怎么定合理呢

**Comment by isnowfy** [comment]
0.5是分界，远大于0.5是正面，远小于0.5是负面，普通的话根据自己的数据情况找个中间合适的范围就好
