### ISSUE TITLE
想知道情感分析的背後的詳細原理

### ISSUE THREAD

**Issue by skydome20** [isnowfy/snownlp#55]
您好
1.
根據您的程式碼，關於情感分析的部分，沒理解錯誤的話，其背後的演算法是基於Bayes的相關模型？
去看過TextBlob的實作後，發現他也是應用Bayes相關的模型(https://textblob.readthedocs.io/en/dev/advanced_usage.html#sentiment-analyzers)

看了你們的東西，但我對於其背後的原理沒有很懂，想知道你們是怎麼用Bayes相關的模型，來進行情感分析的？
想請問您有沒有相關的文獻，或是網站可以參考呢？

2.
TextBlob有做polarity，subjective/objective的分析，不過您的範例只有positive value
那個value值，是否代表越接近1，代表情緒越正向；越接近0，代表情緒越負向呢？

因為TextBlob，在針對英文上面，情緒分析做得很完善
只是中文分析上面，好像還沒有一個針對「極性、正負向」的情緒分析，一個全面且很有效的套件？
目前貌似只有您踏出第一步(而且相當大的一步，感謝)，所以想先充分理解您的東西，未來看有沒有機會來完善中文文字探勘這一塊的缺漏

**Comment by isnowfy** [comment]
您好，
感谢您对本项目的关注，说实话这个项目还有很多不足之处一直没去搞还是非常惭愧的。
情感分析这块我就是利用bayes模型来做的二分类，另外一种常见用法就是利用bayes做垃圾过滤
这里的核心思想就是求P(正向|给定句子)的概率，根据bayes定理等于P(句子|正向)*P(正向)/p(句子)，正比于P(句子|正向)*P(正向)，然后由naive bayes的假设，可以等于P(句子|正向)=相乘P(Wi|正向)，这里Wi表示的是词，相关资料的话可以看看这几个
http://52opencourse.com/235/%E6%96%AF%E5%9D%A6%E7%A6%8F%E5%A4%A7%E5%AD%A6%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E5%A4%84%E7%90%86%E7%AC%AC%E4%B8%83%E8%AF%BE-%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90%EF%BC%88sentiment-analysis%EF%BC%89
http://www.cs.cornell.edu/home/llee/papers/sentiment.pdf
http://www.isnowfy.com/spell-correct/

谢谢

**Comment by skydome20** [comment]
謝謝您提供的reference！
您的snownlp對我目前的研究有極大的幫助，讓我在text mingin的實作和理論上有很大的進步，反倒是我要感謝您的contribute
我會好好讀您提供的資源，有機會再與您分享心得~
