### ISSUE TITLE
情感分析训练中pos.txt和neg.txt有什么区别吗?

### ISSUE THREAD

**Issue by liveao** [isnowfy/snownlp#59]
或者还没有学习到相关内容
我不理解提交两个文件的目的?
或者说这两个文件的区别?
如果自己训练的话, 这两个文件的训练数据应该注意什么?
问的问题可能很弱智啊

**Comment by isnowfy** [comment]
情感分析要区分正向的和负向的，让程序来学习，pos存的就是正向情感的句子，neg是负向情感的句子，如果存一个文件，就要增加表示，告诉程序哪些是正向哪些是负向，自己训练的话就是多找些相关的数据集就好了

**Comment by liveao** [comment]
如何表现正向或者负向情感? 有相关的材料吗?
我看到你库中存好的例子中并没有标注正向负向....在哪里标注呢?

**Comment by isnowfy** [comment]
没有相关材料，根据自己需要的场景自己来定义，举例来说我用了一些买东西的好评作为正向，差评作为负向
我这里就是通过存成两个文件来作为标注的

**Comment by liveao** [comment]
了解... 那训练的时候
我就把正向的评论保存成pos.txt,  负向的评论保存成neg.txt
直接训练就好了
不需要再使用tag或者其他模块分词之类的吧

**Comment by isnowfy** [comment]
是的

**Comment by liveao** [comment]
非常感谢..结贴!
