### ISSUE TITLE
请问如何训练自己的模型？

### ISSUE THREAD

**Issue by yhzhaosicnu** [isnowfy/snownlp#62]
isnowfy, 您好！

我想用snow来训练自己的模型，语料库应该怎么处理？请问seg/data.txt文件是怎么生成的？那些字母是什么意思？谢谢！！

四川师范大学，赵永红

**Comment by yhzhaosicnu** [comment]
还有，提取文本关键字和摘要，用户能不能自己训练呢？

**Comment by rainsun007** [comment]
同问   而且我自己做了分词  4-tag字标注   可是在执行train时会报错
  File "../../snownlp/seg/y09_2047.py", line 68, in train
    for word, tag in sentence:
ValueError: too many values to unpack

**Comment by isnowfy** [comment]
data.txt是人民日报的免费语料，标识都是nlp的通用标识，具体可以查询下人民日报语料相关资料
目前摘要和提取关键词不是训练的方式来做的，所以不能自己训练
