### ISSUE TITLE
from snownlp import SnowNLP 会占用大量内存！

### ISSUE THREAD

**Issue by zengliangju** [isnowfy/snownlp#66]
```
from snownlp import SnowNLP
import time

if __name__ == '__main__':
    while True:
        time.sleep(10)
```

例如，上面这段代码，运行后程序占用近900M的内存，请问有什么优化的方法吗？

**Comment by isnowfy** [comment]
import指令执行之后就会占用内存，因为需要加载需要的字典文件，可以考虑自己修改代码，去掉不需要的加载，或者把相应字典置空

**Comment by xuantianfengwu** [comment]
> import指令执行之后就会占用内存，因为需要加载需要的字典文件，可以考虑自己修改代码，去掉不需要的加载，或者把相应字典置空

请问相应字典置空具体怎么操作呢
