### ISSUE TITLE
有关bayes处理文本输出概率和分词问题

### ISSUE THREAD

**Issue by cenwei1234** [isnowfy/snownlp#67]
由于手头上做一些情感分析相关的研究，最近在研究您的代码，目前存在两个问题，向您请教，如下：
1. 我输入"我爱南方航空" 分词分成 "南方" 和 "航空",这类问题怎么优化；
2. 输出情感值的时候使用的是bayes输出概率，核心代码如下
def classify(self, x):
        print str(x).decode("unicode-escape")
        tmp = {}
        for k in self.d:
            print self.d
            tmp[k] = log(self.d[k].getsum()) - log(self.total)
            for word in x:
                tmp[k] += log(self.d[k].freq(word))
        ret, prob = 0, 0
        for k in self.d:
            now = 0
            try:
                for otherk in self.d:
                    now += exp(tmp[otherk]-tmp[k])
                now = 1/now
            except OverflowError:
                now = 0
            if now > prob:
                ret, prob = k, now
        return (ret, prob)
我看了下，输入的是分词后的结果，那么bayes是怎么样将文本直接输出概率呢，代码有点没看懂，谢谢！

**Comment by isnowfy** [comment]
利用的是贝叶斯垃圾过滤的思路，可以参考这两篇文章
http://www.ruanyifeng.com/blog/2011/08/bayesian_inference_part_two.html
http://www.isnowfy.com/spell-correct/
