### ISSUE TITLE
情感分析训练问题

### ISSUE THREAD

**Issue by Josunarmy** [isnowfy/snownlp#69]
您好！
        我在使用您的方法训练某个特定领域的语料时，得到的是一个.marshal.3的文件，而不是.marshal文件，我把模型的路径改到这个文件后，结果输出的概率和原来用默认的模型输出的一模一样。我是Python新手，自己弄了好久都没解决，还请您不吝赐教！

谢谢！

**Comment by dockersky** [comment]
我也遇到这个问题，.marshal.3重命名成.marshal， 替换neg和pos文件，但是分数还是一样的。你现在处理了吗？
方式如下：
from snownlp import sentiment
sentiment.train('neg.txt', 'pos.txt')
sentiment.save('sentiment.marshal4')

**Comment by ling9601** [comment]
sentiment.train('neg.txt', 'pos.txt')
sentiment.save('sentiment.marshal')

按readme中给出的范例即可，即使后缀为marshal.3,也是输入'sentiment.marshal'
